env:
  global:
  - COMPILE_SDK_VERSION=25
  - BUILD_TOOLS_VERSION=25.0.0
language: android
android:
  components:
  # The BuildTools version used by your project
  - build-tools-$BUILD_TOOLS_VERSION
  # The SDK version used to compile your project
  - android-$COMPILE_SDK_VERSION
script:
- "./gradlew test"
- "./gradlew checkstyle"
- "./gradlew ktlint"
